server:
    port: 2000 #网关端口
spring:
    application:
     name: api-gateway #网关应用名
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8762/eureka/ #注册中心地址

zuul:
  prefix: /api/  #统一前缀
  retryable: false #关闭重试
  routes:
      consumer:
           path: consumer/** #需要映射的uri
           serviceId: spring-cloud-demo-service-consumer #需要转发到的服务ID
